version: "3.9"

name: personal-warehouse-management
services:
  backend:
    build:
      context: ..
      dockerfile: deploy/backend.Dockerfile
    env_file:
      - .env
    environment:
      MONGO_URL: ${MONGO_URL:-mongodb://mongo:27017}
      MONGO_DB_NAME: ${MONGO_DB_NAME:-personal_stock_manage}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    restart: unless-stopped
    container_name: backend

  frontend:
    build:
      context: ..
      dockerfile: deploy/nginx.Dockerfile
      args:
        BACKEND_IP: ${FRONTEND_BACKEND_IP:-localhost:3000}
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    restart: unless-stopped
    container_name: frontend
volumes:
  mongo-data:
